insert into category (category_name, id) values ('Antiques', 20081);
insert into category (category_name, id) values ('Art', 550);
insert into category (category_name, id) values ('Baby', 2984);
insert into category (category_name, id) values ('Books', 267);
insert into category (category_name, id) values ('Business & Industrial', 12576);
insert into category (category_name, id) values ('Cameras & Photo', 625);
insert into category (category_name, id) values ('Cell Phones & Accessories', 15032);
insert into category (category_name, id) values ('Baby & Toddler Clothing', 3082);
insert into category (category_name, id) values ('Clothing & Shoe Care', 106121);
insert into category (category_name, id) values ('Costumes, Reenactment, Theater', 163147);
insert into category (category_name, id) values ('Dancewear', 112425);
insert into category (category_name, id) values ('Kids Clothing, Shoes & Accs', 171146);
insert into category (category_name, id) values ('Mens Accessories', 4250);
insert into category (category_name, id) values ('Mens Clothing', 1059);
insert into category (category_name, id) values ('Mens Shoes', 93427);
insert into category (category_name, id) values ('Uniforms & Work Clothing', 28015);
insert into category (category_name, id) values ('Unisex Clothing, Shoes & Accs', 155184);
insert into category (category_name, id) values ('Vintage', 175759);
insert into category (category_name, id) values ('Wedding & Formal Occasion', 3259);
insert into category (category_name, id) values ('Wholesale, Large & Small Lots', 41964);
insert into category (category_name, id) values ('Womens Accessories', 4251);
insert into category (category_name, id) values ('Womens Clothing', 15724);
insert into category (category_name, id) values ('Womens Shoes', 3034);
insert into category (category_name, id) values ('World & Traditional Clothing', 155240);
insert into category (category_name, id) values ('Coins & Paper Money', 11116);
insert into category (category_name, id) values ('Collectibles', 1);
insert into category (category_name, id) values ('Computers/Tablets & Networking', 58058);
insert into category (category_name, id) values ('Consumer Electronics', 293);
insert into category (category_name, id) values ('Crafts', 14339);
insert into category (category_name, id) values ('Dolls & Bears', 237);
insert into category (category_name, id) values ('DVDs & Movies', 11232);
insert into category (category_name, id) values ('Entertainment Memorabilia', 45100);
insert into category (category_name, id) values ('Everything Else', 99);
insert into category (category_name, id) values ('Gift Cards & Coupons', 172008);
insert into category (category_name, id) values ('Health & Beauty', 26395);
insert into category (category_name, id) values ('Home & Garden', 11700);
insert into category (category_name, id) values ('Jewelry & Watches', 281);
insert into category (category_name, id) values ('Music', 11233);
insert into category (category_name, id) values ('Musical Instruments & Gear', 619);
insert into category (category_name, id) values ('Pet Supplies', 1281);
insert into category (category_name, id) values ('Pottery & Glass', 870);
insert into category (category_name, id) values ('Real Estate', 10542);
insert into category (category_name, id) values ('Specialty Services', 316);
insert into category (category_name, id) values ('Sporting Goods', 888);
insert into category (category_name, id) values ('Sports Mem, Cards & Fan Shop', 64482);
insert into category (category_name, id) values ('Stamps', 260);
insert into category (category_name, id) values ('Tickets & Experiences', 1305);
insert into category (category_name, id) values ('Toys & Hobbies', 220);
insert into category (category_name, id) values ('Travel', 3252);
insert into category (category_name, id) values ('Video Games & Consoles', 1249);